version: '3.4'

services:
  febedb.backend:
    build:
      target: testCerts
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=90bbb875118d4342bb83d35b9503d7c2
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/Certs/febedb.backend.pfx
    volumes:
      - ./Certs/Generated:/Certs
  febedb.frontend:
    build:
      target: testCerts
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=90bbb875118d4342bb83d35b9503d7c2
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/Certs/febedb.frontend.pfx
    volumes:
      - ./Certs/Generated:/Certs
