version: '3.4'

services:
  febedb.db:
    image: ${DOCKER_REGISTRY-}febedbdb
    build:
      context: .
      dockerfile: febedb.db.build/Dockerfile

  febedb.backend:
    image: ${DOCKER_REGISTRY-}febedbbackend
    depends_on:
      - febedb.db
    build:
      context: .
      dockerfile: febedb.backend/Dockerfile
     

  febedb.frontend:
    image: ${DOCKER_REGISTRY-}febedbfrontend
    depends_on:
      - febedb.backend
    build:
      context: .
      dockerfile: febedb.frontend/Dockerfile

